version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lob/postgresql/data
    restart: always

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      VITE_RUBY_HOST: vite
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - vite
      - redis

  vite:
    build: .
    command: bash -c "bin/vite dev"
    environment:
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/myapp

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"

  sidekiq:
    build: .
    command: bundle exec sidekiq -q default -q mailers
    volumes:
      - .:/myapp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_URL: redis://redis:6379
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
    depends_on:
      - db
      - redis

volumes:
  postgres_volume:
  redis:
