version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lob/postgresql/data
    restart: always

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      VITE_RUBY_HOST: vite
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - vite

  vite:
    build: .
    command: bash -c "bin/vite dev"
    environment:
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/myapp

volumes:
  postgres_volume:
