databases:
  - name: myapp
    databaseName: myapp_production
    user: myapp
    plan: free
    region: singapore

services:
  - type: redis
    name: sidekiq-redis
    plan: free
    region: singapore
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections

  - type: web
    name: sidekiq-worker
    env: ruby
    plan: free
    region: singapore
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -q default -q mailers
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: web
    name: myapp
    plan: free
    region: singapore
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
